# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b339bae7820d5ebcea592e6502791bb44bc25426f9e208bb766233bf19bf00ed8dc6e8012a8614588f878c5c53c334b524e2c95729b1fa422db534beb513e128

test:
  secret_key_base: 14c6ac8a1165989eae2394c4990b316d15ad7ace25376177784708b94516a52006de511393412a950a7c67d3c8f5ce59dd1eedcd9ea5d1102b51ec6e64927b6c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
